### ISSUE TITLE
Disabling/uninstalling plugin while highlighting is active does not disable highlighting

### ISSUE THREAD

**Issue by SpacemanRiff** [dseeler/bank-xp-value#1]

**Comment by dseeler** [comment]
This should have been fixed already. Have you updated your client?

**Comment by SpacemanRiff** [comment]
Issue was made shortly after installing the plugin, and Runelite is up to date as of this morning at ~7am. Checking now to see if it has been fixed.

**Comment by SpacemanRiff** [comment]
Ah, I see the issue. It seems this plugin and Bank Value Heatmap plugin don't play well together.

https://user-images.githubusercontent.com/3915208/104112787-83956c00-52b8-11eb-8c65-d48e8661a2e8.mp4

I'll close the issue.

**Comment by dseeler** [comment]
Oh, I see... I hadn’t thought about that. I’ll have that sorted out in the next update. Thanks for letting me know!
