### ISSUE TITLE
Raw Bass not displaying an xp value

### ISSUE THREAD

**Issue by Wrellll** [dseeler/bank-xp-value#17]
Raw Bass does not provide the amount of banked xp when hovered (should be 130xp ea.)

![image_2023-01-20_173109291](https://user-images.githubusercontent.com/67207779/213816898-0d5b8ec7-ba89-456c-809d-fbe2ba729931.png)

![image_2023-01-20_173318987](https://user-images.githubusercontent.com/67207779/213817190-a3cf7ebc-c5a3-486c-bec6-af8906da3ef6.png)

**Comment by dseeler** [comment]
Resolved in #18
