### ISSUE TITLE
Client crashes after odd interaction with Inventory Setup plugin

### ISSUE THREAD

**Issue by ThatCrazyViking** [dseeler/bank-xp-value#2]
I've stumbled across an odd interaction between this plugin and the Inventory Setup plugin that crashes the Runelite client.

The bug occurs as follows:

1. I log in.
2. I go to a bank and click on either the teller or the booth with the 'Bank' option.
3. I enter my pin by clicking on the numbers.
4. When in the bank, I open the following setup with the 'View Setup' option (the eye icon):
{"inventory":[{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":995,"name":"Coins","quantity":40,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":13393,"name":"Xeric\u0027s talisman","quantity":1,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":11806,"name":"Saradomin godsword","quantity":1,"fuzzy":false},{"id":8013,"name":"Teleport to house","quantity":1,"fuzzy":false},{"id":24478,"name":"Open herb sack","quantity":1,"fuzzy":false},{"id":12791,"name":"Rune pouch","quantity":1,"fuzzy":false}],"equipment":[{"id":11865,"name":"Slayer helmet (i)","quantity":1,"fuzzy":false},{"id":6570,"name":"Fire cape","quantity":1,"fuzzy":false},{"id":6585,"name":"Amulet of fury","quantity":1,"fuzzy":false},{"id":4151,"name":"Abyssal whip","quantity":1,"fuzzy":false},{"id":9674,"name":"Proselyte hauberk","quantity":1,"fuzzy":false},{"id":12954,"name":"Dragon defender","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":9676,"name":"Proselyte cuisse","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":22981,"name":"Ferocious gloves","quantity":1,"fuzzy":false},{"id":11840,"name":"Dragon boots","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":11773,"name":"Berserker ring (i)","quantity":1,"fuzzy":false},{"id":22945,"name":"Rada\u0027s blessing 3","quantity":1,"fuzzy":false}],"rune_pouch":[{"id":561,"name":"Nature","quantity":100,"fuzzy":false},{"id":554,"name":"Fire","quantity":500,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false}],"additionalFilteredItems":{"4162":{"id":4162,"name":"Rock hammer","quantity":1,"fuzzy":false},"19634":{"id":19634,"name":"Soul bearer","quantity":1,"fuzzy":false},"9811":{"id":9811,"name":"Farming cape(t)","quantity":1,"fuzzy":false},"9813":{"id":9813,"name":"Quest point cape","quantity":1,"fuzzy":false},"13116":{"id":13116,"name":"Bonecrusher","quantity":1,"fuzzy":false}},"name":"Slayer Melee Prayer","notes":"","highlightColor":{"value":-16711869,"falpha":0.0},"highlightDifference":true,"filterBank":true,"unorderedHighlight":false,"spellBook":0}
5. The client crashes.

This does not occur every time that I login or every time I follow these steps when going to a bank later on in my session. I'll keep trying to find a way to reproduce this bug later today to see if this is indeed the issue.

Here are my error logs from the two days that this has happened:

May 19th: [hs_err_pid2792.log](https://github.com/runelite/runelite/files/6527174/hs_err_pid2792.log)

May 22nd: [hs_err_pid1188.log](https://github.com/runelite/runelite/files/6527175/hs_err_pid1188.log)

Here are my client logs from the two days:

Here are my logs from the two days that this bug occurred. 

[client_2021-05-19.0.log](https://github.com/dillydill123/inventory-setups/files/6533714/client_2021-05-19.0.log)

The crash seems to occur between these two lines:
2021-05-19 16:31:00 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-05-19 16:32:09 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.8.1 (launcher version 1.6.0) starting up, args: none

[client_2021-05-22.0.log](https://github.com/dillydill123/inventory-setups/files/6533716/client_2021-05-22.0.log)

The crash seems to occur between these two lines:
2021-05-22 13:42:18 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2021-05-22 13:43:30 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.8.1 (launcher version 1.6.0) starting up, args: none

After discussing with owner of the Inventory Setup plugin, he believes that the issues is most likely caused by some weird interaction between InventorySetups and Bank Xp Value that causes a nullptr somehow, perhaps during filtering. He suggests having some null checks here: https://github.com/dseeler/bank-xp-value/blob/master/src/main/java/com/bankxpvalue/BankXpValueItemOverlay.java#L61

My issue I opened with the Inventory Setup is here: https://github.com/dillydill123/inventory-setups/issues/87

**Comment by dseeler** [comment]
Thanks for the details. I'm not exactly sure what the root of that error is from, but I can at least implement the null checks as suggested and hopefully that will fix it.

**Comment by dseeler** [comment]
The null check for that line of code has been implemented and merged into the client. Let me know if the error persists. Thanks!
