### ISSUE TITLE
Menu Drag Functionality?

### ISSUE THREAD

**Issue by Elfinlocks** [dseeler/bank-xp-value#8]
Can you please let the xp viewer be draggable? I would be convenient to move elsewhere on my screen so I can look at the viewer and the bank simultaneously.

**Comment by dseeler** [comment]
It is draggable and works just like any other plugin overlay, you just hold the option key (alt on Windows I believe) then click & drag.

https://user-images.githubusercontent.com/47870467/172967993-512f62f7-de9a-463f-8a70-220ff24cb79c.mov
